name: Publish Nuget Package

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Target environment'
                required: true
                default: 'development'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup .Net SDK for All Versions
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: |
            8.x
            9.x
            10.x
          #dotnet-quality: 'preview'

      - name: Modify xUnit Runner Config
        run: |
          echo '{
            "parallelizeAssembly": false,
            "parallelizeTestCollections": false,
            "diagnosticMessages": false
          }' > Tests/IntegrationTests/FastEndpoints/xunit.runner.json

      - name: Run Tests
        run: dotnet test FastEndpoints.sln --configuration Release --verbosity minimal --filter "ExcludeInCiCd!=Yes"

      - name: Make Nuget Packages
        run: dotnet pack -c Release

      - name: Publish To Nuget
        run: dotnet nuget push "Src/**/*.nupkg" -k $NUGET_AUTH_TOKEN -s https://nuget.pkg.github.com/nectar-sistemas/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}


